[package]
name = "ui"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ui_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
client = { path = "../../crates/client" }
futures = "0.3"
notify-rust = "4"
pusher = { path = "../../crates/pusher" }
reqwest = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
settings = { path = "../../crates/settings" }
sentry = "0.34"

