[package]
name = "ui_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
client = { path = "../client" }
settings = { path = "../settings" }
tauri = { version = "2.0", features = ["tray-icon", "unstable"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
