[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.3"
home = "0.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["io-std", "io-util"] }
