[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5"
log = { version = "0.4", features = [] }
serde = { version = "1.0", features = ["derive"] }
simd-json = { version = "0" }
thiserror = "1"
tokio = { version = "1", features = ["io-std", "io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
