[package]
name = "probot"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
client = { path = "../client" }
pusher = { path = "../pusher" }
log = "0.4.22"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
