[workspace]
members = ["client", "client_macros", "encrypt", "encrypt-internal", "extension", "probot", "pusher", "search", "settings", "ui_macros"]
resolver = "2"

[workspace.dependencies]
reqwest = "0.12"
