[workspace]
members = ["client", "client_macros", "encrypt", "encrypt-internal", "extension", "probot", "pusher", "search", "settings", "ui_handlers", "ui_lib", "ui_macros"]
resolver = "2"

[workspace.dependencies]
reqwest = "0.12"
serde_json = "1.0"
thiserror = "2"
