[package]
name = "extension"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-codegen = { version = "*", features = ["isle-in-source-tree"]}
thiserror = { workspace = true }
wasmer = { version = "5", default-features = false, features = ["sys", "wat"] }

[features]
default = ["cranelift"]
cranelift = ["wasmer/cranelift"]
