name: Builds

on:
  push:
    branches: [ "master", "stable" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Setup dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Build
        run: cd ui && npm install && npm run tauri build

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus.exe (x64)
          path: "./ui/src-tauri/target/release/ui.exe"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus_0.1.0_x64_en-US.msi
          path: "./ui/src-tauri/target/release/bundle/msi/prontus_0.1.0_x64_en-US.msi"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus_0.1.0_x64-setup.exe
          path: "./ui/src-tauri/target/release/bundle/nsis/prontus_0.1.0_x64-setup.exe"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: prontus_x86_64 target (Linux)
          path: ./ui/src-tauri/target/release/

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos')
        with:
          name: Prontus.app (aarch64)
          path: ./ui/src-tauri/target/release/bundle/macos/prontus.app

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos')
        with:
          name: prontus_0.1.0_x86_64.dmg
          path: ./ui/src-tauri/target/release/bundle/dmg/prontus_0.1.0_aarch64.dmg