name: Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup ATK
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install librust-atk-dev libgtk-3-dev

      - name: Build with cargo
        run: cargo build -r --all-features

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: prontus_x86_64.exe (Windows)
          path: ./target/release/prontus.exe

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: prontus_x86_64 (Linux)
          path: ./target/release/prontus
